### ISSUE TITLE
[BUG] Absorption and Bleeding

### ISSUE THREAD

**Issue by LtSam** [mcMMO-Dev/mcMMO#4458]
Sometimes bleeding set absorption to NaN, because of this, the player became immortal

**Comment by nossr50** [comment]
Do you have an error log?

**Comment by LtSam** [comment]
No, it's does give an error, but i disabled the swords, axe and unarmed skills in PvP, and it solved the problem.

**Comment by TheBusyBiscuit** [comment]
Could you please re-enable them and post the error via https://www.pastebin.com (or a similar pasting site), then someone can look into it and see if they are able to fix it.

**Comment by samukatb** [comment]
I have the same problem, i tried disabling swords in pvp and the problem is solved. I'm using 1.16 with DeluxeCombat to have 1.8 pvp. And when the player became immortal, it gives this error https://pastebin.com/01Mu1QjM
When i disable swords, a left the server running for 1 week and it solved the bug.

**Comment by TheBusyBiscuit** [comment]
@samukatb 
That error is from DeluxeCombat though, so you may want to report it to them.

**Comment by samukatb** [comment]
> @samukatb
> That error is from DeluxeCombat though, so you may want to report it to them.

I removed deluxe, player still became immortal. But without deluxe, it does not give any error in console

**Comment by TheBusyBiscuit** [comment]
You may still want to report the error to them though nonetheless, so they are able to look into that and fix it.
But that may just be completely unrelated to the issue here, still worth to always report errors when you find them though!

**Comment by timderspieler** [comment]
Hello, timderspieler here (the author of DeluxeCombat),

the given error happens when null or NaN gets passed to my double function. 
@TheBusyBiscuit DeluxeCombat gets his damage by the EntityDamageByEntity event, I guess you set it to NaN or just null. Can you please check that? I just can implement a null check, but I dont think that fixes the main issue.

greetings

**Comment by LtSam** [comment]
@nossr50 
any news about this bug?
I got to the point of having to disable McMMO to prevent the problem.

**Comment by nossr50** [comment]
Rupture was rewritten so I’d be surprised if you still had this issue

**Comment by LtSam** [comment]
Well, I was using version 2.1.188 when I still had a problem with immortality ..
I deactivated the main skills that directly influence PvP, and I had no more problems, as I said earlier ..
It was only when I activated it again that the bug happened again..
Sometimes I noticed an immortal player due to DC errors on the console, when the server dropped TPS.
I am not sure how to replicate the bug, but it is solved when I disable pvp skills.
Swords, axe and unarmed

**Comment by nossr50** [comment]
Still don’t understand how the error is on our side, we aren’t doing anything odd or unusual and every other plugin works fine with us

**Comment by timderspieler** [comment]
@nossr50 as I said @LtSam notices the issue by the errors DeluxeCombat is posting into the console. The NaN exception appears when the damage from the EntityDamageByEntity event is set to null. 

I can add a NaN check which does not fix the issue on your side.

greetings

**Comment by LtSam** [comment]
@nossr50

Any predictions to fix the immortality bug?
I'm still having the problem

**Comment by LtSam** [comment]
@nossr50
I'm still having the problem

**Comment by Chiquis2005** [comment]
I know that this case was already closed, but I have the solution to the problem in case someone has the same problem, the only thing you have to do is to run this command **/attribute {player} minecraft:generic.max_health base set 20
** this will force the user to have 20 health and will not bug him, remember that when running this command the bugee user must remove his armor if he adds extra hearts.
