### ISSUE TITLE
acrobatics prevents falldamage

### ISSUE THREAD

**Issue by homerek111** [mcMMO-Dev/mcMMO#5090]
using 2.2.020 - when falling im almost not receiving any fall damage - sometimes like 0.5 heart only... acrobatics is leveling every fall

**Comment by SirAltF4** [comment]
i also have this bug? wondering if there's a way to disable acrobatics in the meantime?

**Comment by SrBedrock** [comment]
> i also have this bug? wondering if there's a way to disable acrobatics in the meantime?

I believe this problem has already been resolved in the latest version

**Comment by homerek111** [comment]
> > i also have this bug? wondering if there's a way to disable acrobatics in the meantime?
> 
> I believe this problem has already been resolved in the latest version

as i said i use 2.2.020 - its the newest one i think

**Comment by SrBedrock** [comment]
> > > i also have this bug? wondering if there's a way to disable acrobatics in the meantime?
> > 
> > 
> > I believe this problem has already been resolved in the latest version
> 
> as i said i use 2.2.020 - its the newest one i think

![image](https://github.com/user-attachments/assets/107e76e1-dedd-466f-9b9b-3ce1fb85bcf7)

**Comment by homerek111** [comment]
> > > > i also have this bug? wondering if there's a way to disable acrobatics in the meantime?
> > > 
> > > 
> > > I believe this problem has already been resolved in the latest version
> > 
> > 
> > as i said i use 2.2.020 - its the newest one i think
> 
> ![image](https://private-user-images.githubusercontent.com/51332006/369657659-107e76e1-dedd-466f-9b9b-3ce1fb85bcf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NzAyMjIsIm5iZiI6MTcyNjk2OTkyMiwicGF0aCI6Ii81MTMzMjAwNi8zNjk2NTc2NTktMTA3ZTc2ZTEtZGVkZC00NjZmLTliOWItM2NlMWZiODViY2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDAxNTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmODViNDMyYjE0YjljMjE3ZTIyNzg2YjFkOWIxNWNkM2Q2Y2U4MTA0M2UyOTFiNjQxZDgzNjg3MmVkZjI3ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PLk4kzYxn0MGHqR92OgZMwMUk0YejKoPzjeKYtfb3wQ)

oh sorry im dumbed - i use 2.2.021 
but still the same issue - acrobatics protects me from getting damage all the time

**Comment by nossr50** [comment]
Issue should be fixed, open a new ticket if you can reproduce on latest mcMMO with info on steps to reproduce
